services:
  backend:
    build:
      context: ./todo_backend
      dockerfile: Dockerfile
    container_name: todo_backend
    #command: ["sh", "-c", "python todo_backend/manage.py migrate && python todo_backend/manage.py runserver 0.0.0.0:8000"]
    command: python todo_backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./todo_backend:/app
      - ./todo_backend/todo_backend/db.sqlite3:/app/todo_backend/db.sqlite3  # Volume do banco de dados SQLite
    ports:
      - "8000:8000"
#    env_file:
#      - ./todo_backend/.env
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DATABASE_URL=sqlite:///db.sqlite3
    depends_on:
      - db




  frontend:
    build: ./todo-frontend/todo-frontend
    volumes:
      - ./todo-frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
